version: '3.9'
services:
  backend:
    container_name: php_backend
    depends_on:
      db:
        condition: service_healthy
    # image: php:7.4.3-apache
    build: ./
    volumes:
      - ./:/var/www/html/
    ports:
      - 80:80
  db:
    container_name: db
    image: mysql:8.0.28
    ports:
      - 3001:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
